CREATE TABLE IF NOT EXISTS greetings (
	id INTEGER PRIMARY KEY NOT NULL,
	greeting TEXT NOT NULL,
	language TEXT NOT NULL
);

INSERT INTO greetings (id, greeting, language) VALUES
	('19', 'Hello', 'English'),
	('20', 'Hola', 'Spanish'),
	('21', '你好 (Nǐ hǎo)', 'Chinese'),
	('22', 'नमस्ते (Namaste)', 'Hindi'),
	('23', 'হ্যালো (Hyālō)', 'Bengali'),
	('24', 'Olá', 'Portuguese'),
	('25', 'Здравствуйте (Zdravstvuyte)', 'Russian'),
	('26', 'こんにちは (Konnichiwa)', 'Japanese'),
	('27', 'Merhaba', 'Turkish'),
	('28', 'สวัสดี (Sawasdee)', 'Thai'),
	('29', '안녕하세요 (Annyeonghaseyo)', 'Korean'),
	('31', 'Bonjour', 'French'),
	('32', 'שלום (Shalom)', 'Hebrew'),
	('33', 'Salam', 'Arabic'),
	('34', 'سلام (Salaam)', 'Urdu'),
	('35', 'ಹಲೋ (Halo)', 'Kannada'),
	('37', 'வணக்கம் (Vaṇakkam)', 'Tamil'),
	('38', 'നമസ്കാരം (Namaskāram)', 'Telugu'),
	('40', 'Ciao', 'Italian'),
	('41', 'Hej', 'Swedish'),
	('42', 'Здраво (Zdravo)', 'Serbian'),
	('43', 'Ahoj', 'Czech'),
	('44', 'Witam', 'Polish'),
	('45', 'Salut', 'French'),
	('46', 'Γεια σας (Geia sas)', 'Greek'),
	('47', 'Selamat', 'Malay'),
	('48', 'Hyvää päivää', 'Finnish'),
	('49', 'God dag', 'Norwegian'),
	('50', 'ਹੈਲੋ (Hēlō)', 'Punjabi'),
	('52', 'Tere', 'Estonian'),
	('53', 'Labas', 'Lithuanian'),
	('55', 'Kumusta', 'Filipino'),
	('54', 'Sveiki', 'Latvian'),
	('56', 'Gruß Gott', 'Austrian German'),
	('57', 'Hoi', 'Swiss German'),
	('58', 'Përshëndetje', 'Albanian'),
	('59', 'ሰላም (Selam)', 'Amharic'),
	('60', 'Բարև (Barev)', 'Armenian'),
	('61', 'Salam', 'Azerbaijani'),
	('62', 'Kaixo', 'Basque'),
	('63', 'Добры дзень (Dobry dzień)', 'Belarusian'),
	('64', 'Zdravo', 'Bosnian'),
	('65', 'Здравей (Zdravey)', 'Bulgarian'),
	('67', 'Bok', 'Croatian'),
	('69', 'Hallo', 'Dutch'),
	('70', 'Saluton', 'Esperanto'),
	('72', 'გამარჯობა (Gamardzjoba)', 'Georgian'),
	('74', 'Sziasztok', 'Hungarian'),
	('99', 'Soo dhowow', 'Somali'),
	('93', 'Bună', 'Romanian'),
	('111', 'Bawo', 'Yoruba'),
	('76', 'Dia dhuit', 'Irish'),
	('75', 'Halló', 'Icelandic'),
	('101', 'Habari', 'Swahili'),
	('100', 'Halo', 'Sundanese'),
	('95', 'Halò', 'Scottish Gaelic'),
	('108', 'Helo', 'Welsh'),
	('102', 'Kamusta', 'Tagalog'),
	('83', 'Labas', 'Lithuanian'),
	('84', 'Moien', 'Luxembourgish'),
	('109', 'Molo', 'Xhosa'),
	('106', 'Salom', 'Uzbek'),
	('112', 'Sawubona', 'Zulu'),
	('79', 'Slaw', 'Kurdish'),
	('94', 'Talofa', 'Samoan'),
	('88', 'Whanau', 'Maori'),
	('107', 'Xin chào', 'Vietnamese'),
	('87', 'Ħelow', 'Maltese'),
	('98', 'Živijo', 'Slovenian'),
	('105', 'Привіт (Pryvit)', 'Ukrainian'),
	('89', 'Сайн уу (Sain uu)', 'Mongolian'),
	('80', 'Саламатсызбы (Salamatsyzby)', 'Kyrgyz'),
	('103', 'Салом (Salom)', 'Tajik'),
	('78', 'Сәлем (Sälem)', 'Kazakh'),
	('92', 'سلام (Salam)', 'Persian (Farsi)'),
	('96', 'ආයුබෝවන් (Ayubowan)', 'Sinhala'),
	('81', 'ສະບາຍດີ (Sabaidee)', 'Lao');
