CREATE TABLE IF NOT EXISTS languages (
	id INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	category TEXT NOT NULL,
	note TEXT NOT NULL,
	year INTEGER NOT NULL,
	url TEXT NOT NULL
);

INSERT INTO languages (id, category, name, note, year, url) VALUES
	('434', 'Object-oriented', 'Zephir', '"Zephir is a high-level scripting language specially designed for PHP extensions, often used as an alternative to C and C++."', '2014', './zephir'),
	('2', 'Interpreted', 'A++', '"A++ is a simplified, teaching-oriented version of A++, used primarily for teaching programming concepts."', '1992', './a++'),
	('4', 'Assembly', 'A-0 System', '"The A-0 System was the first assembler, developed alongside the machine code based A-0 language."', '1951', './a-0_system'),
	('5', 'Procedural', 'ABAP', 'ABAP (Advanced Business Application Programming) is a procedural programming language developed by SAP for programming commercial applications in its software suite.', '1983', './abap'),
	('6', 'Structured', 'ABC', '"The ABC language, developed at CWI, was designed as an alternative to BASIC and its main goal was to increase programmer productivity."', '1987', './abc'),
	('8', 'Functional', 'ALF', '"ALF, a functional programming language, was created for expressing algorithms in a format close to mathematical notation."', '1990', './alf'),
	('7', 'Modeling', 'AIMMS', 'AIMMS (Advanced Interactive Multidimensional Modeling System) is a modelling language for optimization that was designed to make the process of optimization modelling more efficient.', '1993', './aimms'),
	('9', 'Structured', 'ALGOL 68', '"ALGOL 68, a successor of Algol 60 language, introduced many features and notations of modern programming languages."', '1968', './algol_68'),
	('10', 'Structured', 'ALGOL W', 'ALGOL W was the first attempt to develop a successor to ALGOL 60 before ALGOL 68. It influenced the development of Pascal.', '1966', './algol_w'),
	('11', 'Procedural', 'AMOS', 'AMOS is a procedural programming language designed to create games for Commodore Amiga.', '1990', './amos'),
	('12', 'Procedural', 'AMPL', 'AMPL (A Mathematical Programming Language) is a high-level language for specifying and solving large-scale optimization problems.', '1985', './ampl'),
	('13', 'Array', 'APL', 'APL (A Programming Language) is an influential language based on the mathematical notation of array processing.', '1962', './apl'),
	('15', 'Structured', 'Ada', '"Ada is a structured, statically typed, high-level computer programming language designed for use in large, long-lived applications."', '1980', './ada'),
	('14', 'Server-side', 'ASP.NET', 'ASP.NET is a server-side web application framework designed for web development to produce dynamic web pages.', '2002', './asp.net'),
	('16', 'Functional', 'Agda', '"Agda is a dependent type theory based functional programming language, its development is open-source."', '1999', './agda'),
	('17', 'Reflective', 'Agora', '"Agora is a reflective, concurrent programming language where objects are first-class citizens."', '1994', './agora'),
	('18', 'Functional', 'Aldor', '"Aldor is a highly-level, Turing complete, hybrid functional/imperative programming language."', '1997', './aldor'),
	('19', 'Functional', 'Alice', '"Alice is a freeware functional programming language with rich support for concurrent, distributed, and constraint programming."', '2001', './alice'),
	('21', 'Reactive', 'AmbientTalk', 'AmbientTalk is an experimental object-oriented distributed programming language primarily targeted at writing programs deployed in mobile ad hoc networks.', '2005', './ambienttalk'),
	('22', 'Natural', 'Amharic', 'Amharic is a Semitic language spoken in Ethiopia. It''s the second most spoken Semitic language in the world.', '900', './amharic'),
	('23', 'Functional', 'Amiga E', '"Amiga E, or simply E, is a programming language created by Wouter van Oortmerssen on the Amiga personal computer."', '1994', './amiga_e'),
	('24', 'Scripting', 'AngelScript', 'AngelScript is an extremely flexible cross-platform scripting library designed to allow applications to extend their functionality through external scripts.', '2003', './angelscript'),
	('25', 'Object-oriented', 'Apex', '"Apex is a proprietary language developed by Salesforce.com, inspired by Java and C#, with a syntax that looks like Java and acts like database stored procedures."', '2007', './apex'),
	('26', 'Scripting', 'AppleScript', '"AppleScript is a scripting language created by Apple, enables the automation of tasks on their macOS operating system."', '1993', './applescript'),
	('27', 'Functional', 'Arc', 'Arc is a dialect of the Lisp programming language developed by Paul Graham and Robert Morris.', '2007', './arc'),
	('29', 'Scripting', 'AutoHotkey', '"AutoHotkey is a free, open-source scripting language for Windows that allows users to create scripts for automation of tasks."', '2003', './autohotkey'),
	('30', 'Scripting', 'AutoIt', 'AutoIt v3 is a freeware BASIC-like scripting language designed for automating the Windows GUI and general scripting.', '1999', './autoit'),
	('31', 'Concurrent', 'Axum', '"Axum, previously known as Maestro, is a language oriented towards dataflow programming, and more specifically, towards the concept of isolates."', '2009', './axum'),
	('32', 'Natural', 'Azerbaijani', '"Azerbaijani is an Altaic language that''s written in Perso-Arabic script, but it transitioned to latin then Cyrillic in the past century. It is intelligible with other Turkic languages."', '600', './azerbaijani'),
	('33', 'Procedural', 'B', 'B is a programming language developed at Bell Labs circa 1969. It is the work of Ken Thompson with Dennis Ritchie.', '1969', './b'),
	('34', 'Procedural', 'BASIC', '"BASIC, Beginner''s All-purpose Symbolic Instruction Code, is a family of general-purpose, high-level programming languages whose design philosophy emphasizes ease of use."', '1964', './basic'),
	('35', 'Esoteric', 'BATO', 'BATO is a language designed to be cryptic. It really just serves as a recreation measure for programmers.', '2011', './bato'),
	('37', 'Scripting', 'Bash', 'Bash (Bourne Again SHell) is a Unix shell and command language written by Brian Fox for the GNU Project as a free software replacement for the Bourne shell.', '1989', './bash'),
	('38', 'Scripting', 'Batch', 'Batch is a scripting language for Windows that is used for automating frequently executed commands.', '1962', './batch'),
	('39', 'Esoteric', 'Befunge', 'Befunge is an esoteric programming language with a two-dimensional toroidal grid.', '1993', './befunge'),
	('40', 'Natural', 'Bengali', '"Bengali language spoken in the Indian subcontinent, it is the most eastern branch of the Indo-European languages."', '1000', './bengali'),
	('41', 'Natural', 'Bhojpuri', '"Bhojpuri, an Indo-Aryan language, is native to the north-eastern part of India and the Terai region of Nepal."', '1500', './bhojuri'),
	('42', 'Web development', 'Bigwig', '"Bigwig is a high-level, statically typed programming language for web development with features like session types and effect systems."', '2000', './bigwig'),
	('310', 'Scripting', 'Rebol', '"Rebol is a lightweight, reflective, and homoiconic multi-paradigm language, developed in 1997."', '1997', './rebol'),
	('44', 'Systems', 'BitC', '"BitC is a systems programming language that was designed to be simple, secure and efficient and to ''leapfrog'' the existing C language."', '2006', './bitc'),
	('45', 'Web development', 'Blazor', '"Blazor is a free, open-source Web framework to build Web apps using C# and HTML. It is being developed by Microsoft."', '2018', './blazor'),
	('46', 'Visual', 'Blockly', '"Blockly is a client-side, JavaScript library for creating visual block programming languages and editors."', '2010', './blockly'),
	('47', 'Scripting', 'Blue', 'Blue is a scripting language designed for automation tasks and extending applications.', '2011', './blue'),
	('49', 'Scripting', 'Boa', 'Boa was developed for running scripts that can automate user actions while using less memory and CPU.', '1999', './boa'),
	('50', 'Object-oriented', 'Boo', '"Boo is a statically typed, object-oriented programming language with a Python-inspired syntax. It''s used as a scripting language for the Unity 3D game engine."', '2004', './boo'),
	('51', 'Esoteric', 'Bouncy', '"Bouncy is an esoteric programming language that is designed to be amusing to learn, read, and write."', '2005', './bouncy'),
	('52', 'Esoteric', 'Brainfuck', '"Brainf*** is an esoteric programming language created in 1993 by Urban Müller. Notable for its extreme minimalism, it operates on an array of memory cells."', '1993', './brainfuck'),
	('53', 'Parallel', 'BrookGPU', '"BrookGPU is a compiler and runtime implementation for the Brook programming language, which provides a straightforward means for writing general-purpose programs that run on graphics hardware."', '1997', './brookgpu'),
	('54', 'Object-oriented', 'Builder', 'Builder is an object-oriented development environment for building database applications.', '1998', './builder'),
	('55', 'Natural', 'Bulgarian', 'Bulgarian is a branch of Slavic spoken by people who created the Glagothic alphabet.', '900', './bulgarian'),
	('56', 'Object-oriented', 'Burge', 'Burge is an object-oriented language that was modeled on Algol.', '1976', './burge'),
	('57', 'Object-oriented', 'Caml', '"Caml, short for Categorical Abstract Machine Language, is a general-purpose, powerful language that emphasizes on expressiveness and safety."', '1990', './caml'),
	('58', 'Object-oriented', 'Caribou', '"Caribou is an object-oriented programming language with advanced features for concurrency, distribution and fault-tolerance."', '2010', './caribou'),
	('60', 'Object-oriented', 'Cecil', 'Cecil is a pure object-oriented programming language that was developed at the University of Washington.', '1997', './cecil'),
	('59', 'Natural', 'Cebuano', 'Cebuano language is spoken in the Philippines area and has a heavy impact on local culture and literature.', '1250', './cebuano'),
	('62', 'System programming', 'Chisel', 'Chisel is a hardware description language that supports advanced hardware design using highly parameterized generators and layered domain-specific hardware languages.', '2012', './chisel'),
	('63', 'Structured', 'Chorus', 'The Chorus language is a structured programming language developed at System Development Corporation in the early 1960s.', '1960', './chorus'),
	('64', 'Functional', 'Coconut', '"Coconut is a functional programming language that compiles to Python. It provides simple, elegant, Pythonic syntax."', '2016', './coconut'),
	('65', 'Framework', 'CodeIgniter', 'CodeIgniter is an open-source software rapid development web framework for use in building dynamic web sites with PHP.', '2006', './codeigniter'),
	('66', 'Scripting', 'ColdC', '"ColdC is an object-oriented, concurrent, message-passing language designed for online systems."', '1992', './coldc'),
	('67', 'Parallel', 'Cray AutoTask', 'Cray AutoTask is a parallel processing programming language that uses directives placed in comment fields of Fortran code.', '2010', './cray_autotask'),
	('68', 'Object-oriented', 'Crystal', '"Crystal is a Ruby-inspired statically typed, compiled language with the ability to handle large programs."', '2014', './crystal'),
	('69', 'Workflow', 'Cuneiform', 'Cuneiform is a functional language for large-scale data analysis which compiles to Hadoop.', '2014', './cuneiform'),
	('70', 'Scripting', 'Curl', 'Curl is a reflective object-oriented programming language used for scripting in web pages.', '2000', './curl'),
	('71', 'Functional', 'Curry', '"Curry combines the concepts of functional, logic, and concurrent programming into one language."', '1993', './curry'),
	('72', 'Declarative', 'Cypher', 'Cypher is a declarative graph query language for the Neo4j graph database.', '2011', './cypher'),
	('74', 'Object-oriented', 'D', 'D is a high-level language designed to provide the performance of compiled languages with the ease of interpretation.', '2001', './d'),
	('73', 'Natural', 'Czech', 'Czech evolved from the Proto-Slavic language in the 13th century.', '1250', './czech'),
	('75', 'Logic', 'DAML', 'DAML is a semantic markup language for web resources. It is used for creating ontologies.', '2000', './daml'),
	('76', 'Database', 'DBML', 'DBML (Database Markup Language) is a database language used for defining and manipulating the schema of relational databases.', '2018', './dbml'),
	('77', 'Visual', 'DRAKON', 'DRAKON is a visual language for specifications from the Russian space program.', '1996', './drakon'),
	('78', 'Verification', 'Dafny', 'Dafny is a language designed for program verification. It''s used to prove functional correctness of programs.', '2011', './dafny'),
	('79', 'Object-oriented', 'Dart', 'Dart is a client-optimized language for apps on multiple platforms.', '2011', './dart'),
	('80', 'Database', 'DataFlex', 'DataFlex is a 4GL programming language designed for developing database applications.', '1983', './dataflex'),
	('82', 'Software tools', 'Dialyzer', 'Dialyzer is a static analysis tool for the Erlang programming language.', '2004', './dialyzer'),
	('83', 'Containerization', 'Docker', '"Docker, a PaaS product, uses OS-level virtualization to deliver software in containers."', '2013', './docker'),
	('84', 'Object-oriented', 'Dylan', 'Dylan is a multi-paradigm language that includes support for functional and Object-Oriented programming.', '1992', './dylan'),
	('86', 'Scripting', 'ECMAScript', '"ECMAScript (ES) is a scripting language used for client-side web development, most famously implemented by JavaScript."', '1997', './ecmascript'),
	('87', 'Application framework', 'EFL', 'EFL is a collection of libraries for handling many common tasks in developing apps using the C language.', '2005', './efl'),
	('88', 'Object-oriented', 'Ease', 'Ease is a general purpose parallel programming language which supports a simple form of object-oriented programming.', '1998', './ease'),
	('311', 'Scripting', 'Rexx', '"Launched in 1979, Rexx is an interpreted scripting and command language."', '1979', './rexx'),
	('447', 'Object-oriented', 'CSharp', '"C# encompasses static typing, strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented, and component-oriented programming disciplines. Designed at Microsoft."', '2000', './csharp'),
	('134', 'Declarative', 'Babbage', '"Babbage is a declarative programming language. It was named after Charles Babbage, the inventor of the programmable computer."', '1972', './babbage'),
	('89', 'Natural', 'Egyptian Arabic', '"Egyptian Arabic, an Arabic variety from the Semitic branch of the Afroasiatic language family, is widely spoken in urban Egypt."', '1300', './egyptian_arabic'),
	('90', 'Object-oriented', 'Elan', '"Elan is an imperative, object-oriented programming language with reflection capabilities."', '1984', './elan'),
	('91', 'Functional', 'Elixir', '"Elixir is a dynamic, functional language designed for building scalable and maintainable applications."', '2011', './elixir'),
	('92', 'Functional', 'Elm', 'Elm is a domain-specific programming language for declaratively creating web browser-based graphical user interfaces.', '2012', './elm'),
	('93', 'Scripting', 'Emacs Lisp', 'Emacs Lisp is the scripting language implemented by the Emacs text editor.', '1976', './emacs_lisp'),
	('94', 'Natural', 'English', '"English is a West Germanic language originating from the language spoken by Anglo-Saxons, a cultural group in Britannia during the 5th century."', '500', './english'),
	('95', 'High-level', 'Espaces', '"Espaces is a programming language for writing wide-area, distributed applications."', '2000', './espaces'),
	('96', 'Synchronous', 'Esterel', 'Esterel is a synchronous programming language for the development of complex reactive systems.', '1987', './esterel'),
	('97', 'Object-oriented', 'F3', 'F3 is an object-oriented scripting language and is an early version of the JavaFX Script.', '2005', './f3'),
	('98', 'Macros', 'FORMAC', '"FORMAC, an acronym for FORmula MAnipulation Compiler, is a programming language extension to FORTRAN II and FORTRAN IV."', '1962', './formac'),
	('99', 'Object-oriented', 'Falcon', '"Falcon is an open source, script programming language with a late binding architecture."', '2003', './falcon'),
	('100', 'Object-oriented', 'Fantom', 'Fantom is a general purpose object-oriented programming language that provides features like a scripting language.', '2005', './fantom'),
	('101', 'Type checker', 'Flow', '"Flow is a static type checker, designed to quickly find errors in JavaScript programs."', '2014', './flow'),
	('102', 'User-interface', 'Flux', 'Flux is an architectural pattern used in JavaScript for building user interfaces.', '2012', './flux'),
	('103', 'Stack-based', 'Forth', '"Forth is a stack-based, procedural, imperative computer programming language and environment."', '1970', './forth'),
	('104', 'Natural', 'French', 'French is a Romance language that descended from Vulgar Latin of the Roman Empire.', '700', './french'),
	('105', 'High-level', 'Fresco', 'Fresco is a programming environment for developing highly interactive applications with graphical interfaces.', '1988', './fresco'),
	('108', 'Scripting', 'GRASS', 'Geographic Resources Analysis Support System (GRASS) is a free and open-source GIS software suite used for geospatial data management and analysis.', '1992', './grass'),
	('106', 'Systems', 'GAP', '"Groups, Algorithms, Programming (GAP) is a computer algebra system for computational discrete algebra."', '1986', './gap'),
	('109', 'Column-based', 'GROW', '"GROW is a column-oriented, in-memory, relational, query language based on the tuple calculus."', '1967', './grow'),
	('110', 'Scripting', 'Genie', '"Genie is a modern, general-purpose, high-level programming language in active development."', '2008', './genie'),
	('111', 'Natural', 'German', 'German is a West Germanic language that has the same roots as English and Dutch languages.', '700', './german'),
	('112', 'Software tools', 'Getafix', 'Getafix is an automated source code repair tool capable of fixing bugs.', '2017', './getafix'),
	('113', 'Object-oriented', 'Gnome', '"Gnome is a feature-rich language with support for internet protocols, X-Windows graphics, and more."', '1997', './gnome'),
	('114', 'Functional', 'Gofer', '"Gofer is a functional programming language, a dialect of Haskell, and it emphasizes the value of strong typing."', '1991', './gofer'),
	('115', 'Object-oriented', 'Gosu', '"Gosu is statically-typed, open-source language that compiles to Java Virtual Machine (JVM) bytecode."', '2002', './gosu'),
	('116', 'Virtual machine', 'GraalVM', '"GraalVM, a high-performance runtime, offers a comprehensive solution to run programs faster."', '2018', './graalvm'),
	('117', 'Language', 'GraphQL', 'GraphQL provides an efficient and powerful alternative to REST and offers developers greater flexibility and efficiency.', '2015', './graphql'),
	('118', 'Natural', 'Greek', '"Greek, one of the world''s oldest recorded living languages, has been documented in 34 centuries of written records."', '0', './greek'),
	('119', 'Object-oriented', 'Groovy', 'Apache Groovy is an agile and dynamic language for the Java Virtual Machine.', '2003', './groovy'),
	('120', 'Natural', 'Gujarati', '"Gujarati, native to the Indian state of Gujarat, is a part of the greater Indo-European language family."', '1100', './gujarati'),
	('121', 'Scripting', 'HaXml', '"HaXml is a collection of utilities for parsing, filtering, transforming, and generating XML documents using Haskell."', '2000', './haxml'),
	('122', 'Hybrid', 'Hafren', 'Hafren is a programming language capable of automatic code generation for XML data structures.', '2004', './hafren'),
	('123', 'Procedural', 'Harbour', 'Harbour is a modern procedural programming language that is backward compatible with Clipper.', '1999', './harbour'),
	('124', 'Scripting', 'Hartmann', '"Hartmann is a Basic-like computer language, used for generating numerical control (NC) code."', '1980', './hartmann'),
	('125', 'Object-oriented', 'High Five', '"High Five is an object-oriented language designed for high-level, complex programming tasks."', '1995', './high_five'),
	('127', 'Natural', 'Hmong', '"Hmong is a language spoken by the Hmong people, an ethnic group that immigrated due to conflicts with China."', '0', './hmong'),
	('126', 'Natural', 'Hindustani', '"Hindustani encompasses both Hindi and Urdu - major languages in India and Pakistan, respectively."', '700', './hindustani'),
	('128', 'Object-oriented', 'Hop', 'Hop is a multi-tier language for programming the Web 2.0. It is designed for writing highly interactive applications.', '2006', './hop'),
	('129', 'Natural', 'Hungarian', 'Hungarian is the official language of Hungary. It''s part of the Uralic family of languages.', '900', './hungarian'),
	('175', 'Dataflow', 'ECL', '"ECL (Enterprise Control Language) is a declarative, data-centric programming language for distributed data processing."', '2000', './ecl'),
	('194', 'Scripting', 'GNU E', 'GNU E is a scripting language that was introduced in 1999 by the GNU project.', '1999', './gnu_e'),
	('217', 'Object-oriented', 'IDL', 'IDL (Interactive Data Language) is an object-oriented programming language used for data analysis.', '1977', './idl'),
	('218', 'Scripting', 'IML', 'IML is a scripting language developed in 1998.', '1998', './iml'),
	('219', 'Object-oriented', 'ISLISP', 'ISLISP is an object-oriented programming language. It is a variant of Lisp.', '1997', './islisp'),
	('220', 'Scripting', 'Icon', '"Icon is a high-level, general-purpose programming language with a large range of features for processing data structures and character strings."', '1977', './icon'),
	('221', 'Object-oriented', 'Idris', '"Idris is an experimental functional programming language with dependent types, which was created by Edwin Brady."', '2009', './idris'),
	('222', 'Object-oriented', 'Ignition', 'Ignition is an object-oriented programming language. It was introduced in 2018.', '2018', './ignition'),
	('223', 'Natural', 'Indonesian', '"Indonesian is the official language of Indonesia. It is a standardized variety of Malay, an Austronesian language that has been used as a lingua franca in the Indonesian archipelago for centuries."', '100', './indonesian'),
	('224', 'Object-oriented', 'Ioke', '"Ioke is an object-oriented programming language, a member of the Lisp-family of languages, and a prototype-based programming language."', '2007', './ioke'),
	('226', 'Natural', 'Italian', '"Italian is a Romance language of the Indo-European language family. It is the official language in Italy, Switzerland, San Marino, Vatican City, and western Istria."', '900', './italian'),
	('225', 'Natural', 'Iranian Persian', '"Iranian Persian, also known as Farsi, is an Indo-European language and is the official language of Iran."', '400', './iranian_persian'),
	('227', 'Object-oriented', 'JC', 'JC is an object-oriented programming language developed in 1997.', '1997', './jc'),
	('228', 'Software tools', 'JHipster', 'JHipster is a software tool for generating application code that uses Angular or React for front-end development and Spring Boot as back-end.', '2013', './jhipster'),
	('230', 'Concurrent', 'Janus', 'Janus is a concurrent programming language featuring guarded command programming.', '1981', './janus'),
	('229', 'Software tools', 'JUnit', 'JUnit is a software tool for unit testing in Java programming language.', '2000', './junit'),
	('231', 'Natural', 'Japanese', '"Japanese is an East Asian language spoken by about 128 million people, primarily in Japan, where it is the official and national language."', '700', './japanese'),
	('233', 'Scripting', 'JavaScript', '"JavaScript, often abbreviated as JS, is a high-level, just-in-time compiled, object-oriented programming language."', '1995', './javascript'),
	('234', 'Rule-based', 'KRL', '"KRL (KUKA Robot Language) is a proprietary, rule-based programming language for industrial robots made by KUKA Robotics."', '1995', './krl'),
	('235', 'Object-oriented', 'Kaleidoscope', 'Kaleidoscope is an object-oriented programming language. It was introduced in 2000.', '2000', './kaleidoscope'),
	('236', 'Natural', 'Kannada', '"Kannada is a Dravidian language spoken predominantly by people of Karnataka in Southwestern India and by significant linguistic minorities in the states of Maharashtra, Andhra Pradesh, Tamil Nadu, Telangana, Kerala and abroad."', '500', './kannada'),
	('237', 'Object-oriented', 'Kawa', 'Kawa is a dialect of the Lisp programming language designed for integration with Java and written in the Java language.', '2008', './kawa'),
	('238', 'Natural', 'Korean', 'Korean is an East Asian language spoken by about 77 million people. The official language of both South Korea and North Korea.', '1500', './korean'),
	('239', 'Shell', 'KornShell', 'KornShell is a Unix shell designed for both interactive and scripting use.', '1983', './kornshell'),
	('240', 'Object-oriented', 'Kotlin', '"Kotlin is a cross-platform, statically typed, modern programming language. It is designed to interoperate fully with Java and the JVM version of its standard library."', '2011', './kotlin'),
	('241', 'Natural', 'Kurdish', 'Kurdish is an Indo-European language. It was developed from Old Persian and is spoken by the Kurdish people in Western Asia.', '700', './kurish'),
	('242', 'Object-based', 'Kyro', 'Kyro is an object-based programming language that was introduced in 2015.', '2015', './kyro'),
	('243', 'Object-oriented', 'Labyrinth', 'Labyrinth is an object-oriented programming language that was developed in 2000.', '2000', './labyrinth'),
	('244', 'Object-oriented', 'Lasso', '"Lasso is an object-oriented, interpreter (scripting) language, and server for developing web applications."', '1995', './lasso'),
	('245', 'Object-oriented', 'Linq', 'LINQ (Language Integrated Query) is a Microsoft .NET Framework component that adds native data querying capabilities to .NET languages.', '2007', './linq'),
	('246', 'Object-oriented', 'Lisp', 'Lisp is a family of programming languages with a long history and a distinctive design philosophy.', '1958', './lisp'),
	('247', 'Natural', 'Lithuanian', '"Lithuanian is a Baltic language, being the most conservative living Indo-European language. It was the language of the Grand Duchy of Lithuania."', '0', './lithuanian'),
	('248', 'Object-oriented', 'Locomotive', 'Locomotive is an object-oriented programming language that was introduced in 1991.', '1991', './locomotive'),
	('249', 'Object-oriented', 'Logtalk', 'Logtalk is an object-oriented logic programming language that can use most Prolog implementations as a back-end compiler.', '1998', './logtalk'),
	('250', 'Object-oriented', 'Lotus', 'Lotus is an object-oriented programming language that was introduced by Lotus Software in 1989.', '1989', './lotus'),
	('251', 'Scripting', 'Lua', '"Lua is a high-level, multi-paradigm scripting language designed as a lightweight scripting language with extensible semantics as a primary goal."', '1993', './lua'),
	('252', 'Math Computation', 'MATH-MATIC', '"MATH-MATIC is a precursor to A-1, A-2, A-3 languages. It provides low-level, system-specific instructions."', '1953', './math-matic'),
	('254', 'Natural', 'Malagasy', 'Malagasy is an Austronesian language and the national language of Madagascar. It is also spoken by minorities in neighboring Indian Ocean islands.', '200', './malagasy'),
	('255', 'Natural', 'Malay', '"Malay is a major language of the Austronesian language family. it is the official language of Brunei, Malaysia, and Indonesia."', '1500', './malay'),
	('256', 'Natural', 'Mandarin Chinese', 'Mandarin Chinese is a group of related Sinitic languages spoken across most of northern and southwestern China. It is the most spoken language in the world.', '100', './mandarin_chinese'),
	('257', 'Natural', 'Marathi', '"Marathi is an Indo-Aryan language spoken predominantly by people of Maharashtra, India. It is descended from Sanskrit through Pali, Maharashtri and Maharashtra-Prakrit."', '1300', './marathi'),
	('258', 'Object-oriented', 'Maude', 'Maude is a high-performance logical framework and object-oriented programming language. It is based on rewriting logic.', '1996', './maude'),
	('259', 'Software framework', 'Meteor', '"Meteor is an open-source platform for web, mobile and desktop applications. It is written using Node.js."', '2012', './meteor'),
	('261', 'Object-oriented', 'Mirah', 'Mirah is an object-oriented programming language. It was introduced in 2011.', '2011', './mirah'),
	('262', 'Database', 'Mnesia', 'Mnesia is a distributed soft real-time database management system. It is written in Erlang.', '1995', './mnesia'),
	('263', 'Object-oriented', 'Mocha', 'Mocha is an object-oriented programming language that was introduced in 2012.', '2012', './mocha'),
	('264', 'Object-oriented', 'NCL', 'NCL (Network Common Lisp) is an object-oriented programming language developed in the late 1970s.', '1977', './ncl'),
	('265', 'Object-oriented', 'Nanook', 'Nanook is primarily an object-oriented programming language developed in 1999.', '1999', './nanook'),
	('266', 'Natural', 'Nepali', 'Nepali is an Indo-Aryan language with a complex inflectional morphology. It uses pitch contour to alter the meaning of words.', '1300', './nepali'),
	('267', 'Educational', 'NetLogo', '"NetLogo is predominantly used for educational purposes, designed in 1999."', '1999', './netlogo'),
	('269', 'Software framework', 'NodeJS', 'Node.js is a Javascript runtime built on Chrome''s V8 JavaScript engine.', '2009', './nodejs'),
	('268', 'Configuration', 'Nginx', 'Nginx configuration is built for the configuration of nginx HTTP servers and was released in 2004.', '2004', './nginx'),
	('270', 'Object-oriented', 'OCamlSharp', '"OCamlSharp is an object-oriented variant of the OCaml language, introduced in 2004."', '2004', './ocamlsharp'),
	('271', 'Object-oriented', 'Objective Caml', '"Objective Caml is an object-oriented functional language from the ML family, established in 1996."', '1996', './objective_caml'),
	('272', 'Software framework', 'Ocsigen', 'Ocsigen is a software framework introduced in 2005.', '2005', './oscigen'),
	('273', 'Web framework', 'Opa', '"Opa is a web-based framework for JavaScript, released in 2011."', '2011', './opa'),
	('274', 'Object-oriented', 'Ops5', 'Ops5 is an object-oriented language developed in 1981.', '1981', './ops5'),
	('275', 'Object-oriented', 'Oracle', '"Oracle is an object-oriented database language, first launched in 1977."', '1977', './oracle'),
	('276', 'Procedure-oriented', 'Oriel', 'Oriel is a procedure-oriented programming language that appeared in 1981.', '1981', './oriel'),
	('277', 'Natural', 'Oromo', '"Oromo is a Southern Cushitic language predominantly spoken in Ethiopia, dating back to 1500."', '1500', './oromo'),
	('278', 'Object-oriented', 'Orwell', 'Orwell is an object-oriented language that was launched in 1984.', '1984', './orwell'),
	('279', 'Object-oriented', 'Otter', 'Otter is an object-oriented language developed in 1987.', '1987', './otter'),
	('280', 'Object-oriented', 'Owl', '"Established in 2010, Owl is an object-oriented language."', '2010', './owl'),
	('281', 'Structured', 'PACTOL', '"PACTOL is a structured programming language, released in 1961."', '1961', './pactol'),
	('282', 'Object-oriented', 'PLatte', '"PLatte is an object-oriented programming language, developed in 1993."', '1993', './platte'),
	('283', 'Object-oriented', 'Packrat', 'Packrat is an object-oriented language that first appeared in 2015.', '2015', './packrat'),
	('285', 'Object-oriented', 'Parrot', '"Parrot, released in 2001, is an object-oriented language."', '2001', './parrot'),
	('286', 'Structured', 'Pascal', '"Developed in 1970, Pascal is a structured programming language."', '1970', './pascal'),
	('287', 'Object-oriented', 'Pharen', '"Pharen, which emerged in 2014, is an object-oriented programming language."', '2014', './pharen'),
	('288', 'Object-oriented', 'Pico', '"Launched in 2011, Pico is an object-oriented language."', '2011', './pico'),
	('289', 'Functional', 'Pict', '"Pict, established in 1997, is a functional programming language."', '1997', './pict'),
	('290', 'Scripting', 'Pike', '"Established in 1996, Pike is a scripting language."', '1996', './pike'),
	('292', 'Object-oriented', 'Pnuts', 'Pnuts is an object-oriented language that first appeared in 1997.', '1997', './pnuts'),
	('294', 'Object-oriented', 'Polymer', '"Polymer, launched in 2013, is an object-oriented language."', '2013', './polymer'),
	('295', 'Procedural', 'Pop-11', '"Developed in 1976, Pop-11 is a procedural language used for teaching and research."', '1976', './pop-11'),
	('296', 'Natural', 'Portuguese', '"Portuguese is a Romance language native to Portugal, dating back to 900."', '900', './portuguese'),
	('297', 'Object-oriented', 'Processing', '"Processing, launched in 2001, is designed to introduce beginners to computer programming within a visual context."', '2001', './processing'),
	('298', 'Logic', 'Prolog', '"Prolog is a logic-based programming language associated with artificial intelligence and computational linguistics, established in 1972."', '1972', './prolog'),
	('299', 'Object-oriented', 'Proxima', '"Proxima, launched in 2011, is an object-oriented language."', '2011', './proxima'),
	('300', 'Configuration management', 'Puppet', '"Leveraging a declarative, model-based approach to IT automation, Puppet was developed in 2005."', '2005', './puppet'),
	('302', 'Scripting', 'Python', '"Python is an interpreted, high-level general-purpose programming language. Its design philosophy emphasizes code readability, and its syntax allows programmers to express concepts in fewer lines of code than would be possible in such as C++ or Java, launched in 1991."', '1991', '/python'),
	('303', 'Array', 'Q', '"Launched in 2003, Q is a programming language for array processing, and resembles K in terms of syntax."', '2003', './q'),
	('304', 'Object-oriented', 'Qorpora', '"Qorpora, established in 1993, is an object-oriented language."', '1993', './qorpora'),
	('305', 'Scripting', 'R', '"R is a scripting language predominantly used by statisticians and data miners for developing statistical software and data analysis, released in 2000."', '2000', './r'),
	('307', 'Object-oriented', 'RPL', '"RPL is a software platform for computer algebra systems, especially designed for educational purposes. RPL was initially launched in 2003."', '2003', './rpl'),
	('306', 'Structured', 'RPG', 'RPG (Report Program Generator) is a high-level programming language for business applications; it was developed in the 1950s.', '1959', './rpg'),
	('308', 'Object-oriented', 'Rascal', '"Introduced in 2005, Rascal is an object-oriented programming language."', '2005', './rascal'),
	('309', 'Structured', 'Ratfor', '"Ratfor is a preprocessor for a dialect of Fortran. It was designed to introduce structured programming elements to the Fortran IV language, developed in 1975."', '1975', './ratfor'),
	('312', 'Natural', 'Romanian', '"Romanian is a Romance language mainly spoken in Romania and Moldova, dating back to 1500."', '1500', './romanian'),
	('313', 'Scripting', 'Ruby', '"Ruby is an interpreted, high-level general-purpose programming language that supports multiple programming paradigms, including procedural, object-oriented, and functional programming."', '1995', './ruby'),
	('314', 'System programming', 'Rust', '"Rust is a multi-paradigm system programming language built for performance and safety, especially safe concurrency, developed in 2010."', '2010', './rust'),
	('315', 'Dataflow', 'SISAL', '"Acronym for Streams and Iteration in a Single Assignment Language, SISAL is a general-purpose single assignment functional programming language with strict semantics."', '1983', './sisal'),
	('316', 'Object-oriented', 'Scala', '"Scala is a modern multi-paradigm programming language designed to express patterns in a concise, elegant, and type-safe way."', '2003', './scala'),
	('317', 'Functional', 'Scheme', '"Scheme is a programming language that supports multiple paradigms, including functional and imperative programming. It was one of the first programming languages to support first-class continuations."', '1975', './scheme'),
	('318', 'Procedural', 'Seed7', 'Seed7 is a extensible general-purpose programming language designed by Thomas Mertes. It is syntactically similar to Pascal and Ada.', '2005', './seed7'),
	('319', 'Object-oriented', 'Self', 'Self is an object-oriented programming language based on the concept of prototypes. Self was used as an experimental test system for language design in the 1990s.', '1987', './self'),
	('320', 'Natural', 'Sinhalese', '"Spoken by the Sinhalese people of Sri Lanka, Sinhalese is an Indo-Aryan language that is a descendant of the ancient Indian Brahmi script."', '200', './sinhalese'),
	('321', 'Object-oriented', 'Smalltalk', '"Considered the first truly object-oriented programming language, Smalltalk was created as the language to underpin the “new world” of computing exemplified by human-computer interaction."', '1972', '/smalltalk'),
	('322', 'Contract-oriented', 'Solidity', '"Solidity is a statically-typed programming language built for the Ethereum platform to write smart contracts, released in 2014."', '2014', './solidity'),
	('323', 'Natural', 'Somali', '"Somali is an Afro-Asiatic language, belonging to the family''s Cushitic branch. It is spoken as a mother tongue by ethnic Somalis in Greater Somalia and the Somali diaspora."', '200', './somali'),
	('326', 'Natural', 'Sundanese', '"Sundanese is a language spoken in the western part of the Indonesian Java island, dated to 1500."', '1500', './sundanese'),
	('324', 'Data processing', 'Splunk Processing Language', '"Splunk Processing Language (SPL) is used for searching, filtering, and manipulating the data for generating statistics and visualizations."', '2007', './splunk_processing_language'),
	('325', 'Functional', 'Standard ML', '"Standard ML (SML) is a general-purpose, modular, functional programming language with compile-time type checking and type inference."', '1983', './standard_ml'),
	('327', 'Object-oriented', 'Swift', '"Swift is a powerful and intuitive programming language for macOS, iOS, watchOS, and tvOS. It is designed to work with Apple''s Cocoa and Cocoa Touch frameworks and the large body of existing Objective-C code written for Apple "', '2014', './swift'),
	('328', 'Text editor', 'TECO', 'A text editor developed at the Massachusetts Institute of Technology (MIT) in the 1960s that was for many years the standard editor on DEC systems.', '1963', './teco'),
	('329', 'Object-oriented', 'TOM', 'TOM is an object-oriented programming language that advocates the composition of programs by way of communicating concurrent objects.', '1996', './tom'),
	('331', 'Systems', 'TXL', 'TXL is a source transformation language widely used in research and is used in software renovation factories.', '1992', './txl'),
	('330', 'Object-oriented', 'TTCN', 'TTCN (Testing and Test Control Notation) is a specification language developed by the European Telecommunications Standards Institute and used to implement testing software.', '1991', './ttcn'),
	('332', 'Natural', 'Tamil', '"Tamil is a Dravidian language predominantly spoken by the Tamil people of India and Sri Lanka, and by the Tamil diaspora and Sri Lankan Moors."', '300', './tamil'),
	('333', 'Scripting', 'Tcl', 'Tool Command Language (Tcl) is a dynamic language that is designed for extensibility and embedded use.', '1989', './tcl'),
	('335', 'Object-oriented', 'Teasy', 'Teasy is an object-oriented programming language developed in 1984 for teaching object-oriented programming.', '1984', './teasy'),
	('336', 'Natural', 'Telugu', '"Telugu is a Dravidian language spoken predominantly in the Indian states of Andhra Pradesh, Telangana and Yanam by the Telugu people and it is one of 22 scheduled languages of India."', '1000', './telugu'),
	('337', 'RPC framework', 'Thrift', '"Originally developed by Facebook, Thrift is an interface definition language and binary communication protocol used for defining and creating services for numerous languages."', '2007', './thrift'),
	('338', 'High-level', 'Thrust', 'Thrust is a high-level thrust library implemented with expression templates and includes a number of CUDA-specific extensions.', '2005', '/thrust'),
	('341', 'Systems', 'Thyrd', '"Thyrd is an interactive, visual programming language and environment. Thyrd can be modified while it is running, enabling live programming."', '2008', './thyrd'),
	('342', 'Object-oriented', 'Tipo', '"Tipo is an object-oriented programming language. It supports polymorphism through interface, mixin and subclass relationships."', '1991', './tipo'),
	('343', 'Object-oriented', 'Tmu', 'Tmu is an experimental programming language supporting a powerful form of data abstraction and object-oriented programming.', '2011', './tmu'),
	('344', 'Object-oriented', 'Tom', 'Tom is a pattern matching compiler for Java. It is a link between functional and object-oriented programming.', '2015', './tom'),
	('345', 'Object-oriented', 'Topaz', '"Topaz is a high-performance, dynamic, object-oriented programming language which is focused on simplicity and maintainability."', '2012', './topaz'),
	('346', 'Procedural', 'Transact-SQL', 'Transact-SQL is Microsoft''s and Sybase''s proprietary extension to the SQL language. Microsoft''s implementation ships in the person of MS SQL Server.', '1987', './transact-sql'),
	('347', 'Object-oriented', 'Traveler', 'Traveler is an object-oriented language designed for use in travel industry software.', '1984', './traveler'),
	('348', 'Object-oriented', 'TreeHugger', 'TreeHugger is an object-oriented language that builds upon the ideas introduced in the Scheme language.', '2011', './treehugger'),
	('349', 'Systems', 'Trill', 'Trill is a systems programming language that focuses on providing access to the raw power of the machine.', '2000', './trill'),
	('350', 'Systems', 'Trindle', 'Trindle is a systems programming language designed with portability and modularity in mind.', '2005', './trindle'),
	('353', 'Natural', 'Turkish', '"Turkish is a member of the Oghuz group of languages, a subgroup of the Turkic language family. The language has taken many of its structural characteristics from Arabic and Persian."', '800', './turkish'),
	('354', 'Object-oriented', 'Tycoon', 'Tycoon is an object-oriented programming language with features for structuring large systems and concurrent computation.', '2014', './tycoon'),
	('355', 'Object-oriented', 'TypeScript', 'TypeScript is a free and open-source programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript and adds optional static typing to the language.', '2012', './typescript'),
	('356', 'Object-oriented', 'UIS', '"UIS is an object-oriented programming language that simplifies the development of complex, modular programs."', '1981', './uis'),
	('357', 'Object-oriented', 'ULISP', '"ULISP is an object-oriented dialect of Lisp, featuring a rich set of object-oriented features."', '1991', './ulisp'),
	('359', 'Object-oriented', 'Ultrix', 'Ultrix is an obsolete DEC OS for PDP-11 modeled after Unix. The Ultrix-11 version supported System V and BSD features.', '1978', './ultrix'),
	('360', 'Object-oriented', 'UniLang', 'UniLang (Universal Language) is a component-oriented programming language allowing components to be written in multiple languages.', '1981', './unilang'),
	('361', 'Systems', 'Unicon', '"Unicon is a high-level, open-source, imperative programming language which is oriented towards string processing and pattern matching."', '2000', './unicon'),
	('362', 'Object-oriented', 'Unix', '"Unix is a family of multitasking, multiuser computer operating systems that derive from the original AT&T Unix, development starting in the 1970s at the Bell Labs research center by Ken Thompson, Dennis Ritchie, and others."', '1970', './unix'),
	('363', 'Scripting', 'Unix shell', 'The Unix shell is a command-line interpreter that provides a user interface for the Unix operating system and for Unix-like systems.', '1979', './unix_shell'),
	('364', 'Game programming', 'UnrealScript', 'UnrealScript (often abbreviated to UScript) is Unreal Engine''s native scripting language used for authoring game code and gameplay events before the release of Unreal Engine 4.', '1998', './unrealscript'),
	('365', 'Object-oriented', 'Ursala', 'Ursala is an object-oriented programming language with a focus on simplicity and readability.', '1991', './ursala'),
	('366', 'System programming', 'VHDL', '"VHDL (VHSIC Hardware Description Language) is a hardware description language used in electronic design automation to describe digital and mixed-signal systems such as field-programmable gate arrays and integrated "', '1987', './vhdl'),
	('368', 'Object-oriented', 'VR-1', 'VR-1 is an object-oriented programming language designed for creating virtual reality applications', '1991', './vr-1'),
	('367', 'Object-oriented', 'VR', 'VR is an object-oriented programming language designed for creating virtual reality applications.', '1992', './vr'),
	('370', 'Object-oriented', 'VS', 'VS is an object-oriented programming language developed by Microsoft Corporation. It is part of the Visual Studio suite of programming tools and supports a variety of programming paradigms.', '1995', './vs'),
	('369', 'Object-oriented', 'VR-2', 'VR-2 is an object-oriented programming language designed for creating virtual reality applications', '1991', './vr-2'),
	('371', 'Object-oriented', 'VSL', 'VSL is an object-oriented programming language.', '1991', './vsl'),
	('372', 'Object-oriented', 'VT', 'VT is an object-oriented programming language.', '1998', './vt'),
	('373', 'Object-oriented', 'Vajr', '"Vajr is an object-oriented, dynamic, reflective, general-purpose programming language. It has syntax similar to Smalltalk."', '1999', './vajr'),
	('374', 'Object-oriented', 'Vala', 'Vala is an object-oriented programming language with a self-hosting compiler that generates C code and uses the GObject system.', '2006', './vala'),
	('376', 'Object-oriented', 'Vamp', '"Vamp is an object-oriented, interpreted, visually-oriented language. It is intended for non-programmers and is suitable for a wide range of problem domains."', '1991', './vamp'),
	('377', 'Object-oriented', 'Vash', 'Vash is an object-oriented programming language. It has a dynamic type system and automatic memory management and makes use of first-class and higher-order functions.', '2011', './vash'),
	('378', 'Object-oriented', 'Vax', '"Vax is an object-oriented programming language with a focus on flexibility, speed and simplicity."', '1977', './vax'),
	('379', 'Object-oriented', 'Vector Math', 'Vector Math is an object-oriented mathematical programming language.', '2008', './vector_math'),
	('380', 'Object-oriented', 'Venari', 'Venari is an object-oriented programming language with a focus on advanced OO concepts.', '1999', './venari'),
	('381', 'System programming', 'Verilog', 'Verilog is a hardware description language used to model electronic systems. It is most commonly used in the design and verification of digital circuits at the register-transfer level of abstraction.', '1984', './verilog'),
	('382', 'Object-oriented', 'Vic', 'Vic is an object-oriented programming language that puts emphasis on object usage rather than implementation.', '1991', './vic'),
	('383', 'Natural', 'Vietnamese', '"Vietnamese is an Austroasiatic language that originated in Vietnam, where it is the national and official language. Vietnam is also the language''s largest speaking population. It is the native language of the Vietnamese (Kinh) "', '300', './vietnamese'),
	('384', 'Object-oriented', 'Vish', 'Vish is an object-oriented scripting language with a focus on flexibility and simplicity.', '2017', './vish'),
	('385', 'Scripting', 'Visual Basic', 'Visual Basic is a third-generation event-driven programming language from Microsoft for its Component Object Model (COM) programming model first released in 1991.', '1991', './visual_basic'),
	('386', 'Object-oriented', 'Visual Basic .NET', '"Visual Basic .NET (VB.NET) is a multi-paradigm, object-oriented programming language, implemented on the .NET Framework."', '2001', './visual_basic_.net'),
	('387', 'Database', 'Visual FoxPro', '"Visual FoxPro is an object-oriented programming environment which includes a data-centric, object-oriented language, a database engine and a set of productivity tools for business application development."', '1989', '/visual_foxpro'),
	('388', 'Object-oriented', 'Vlisp', '"Vlisp is an object-oriented programming language. It is a version of the programming language Lisp, specially designed for voice applications."', '1978', './vlisp'),
	('389', 'Object-oriented', 'Vose', 'Vose is an object-oriented programming language.', '1999', './vose'),
	('390', 'Object-oriented', 'Vox', 'Vox is an object-oriented programming language that focuses on simplicity and correctness.', '2010', './vox'),
	('391', 'Object-oriented', 'Vu', 'Vu is an object-oriented programming language.', '1996', './vu'),
	('407', 'Query', 'XQuery', '"XQuery is a standardized language for combining documents, databases, Web pages and almost anything else. XQuery is about querying XML data, but not limited to XML – it also handles other forms of data, such as relational databases and "', '2001', './xquery'),
	('408', 'Markup', 'XSLT', '"XSLT (Extensible Stylesheet Language Transformations) is a language for transforming XML documents into other XML documents, or other formats such as HTML, XHTML, plain text, or XSL-FO."', '1999', './xslt'),
	('409', 'Object-oriented', 'Xbase', 'Xbase is an object-oriented extension of the Clipper computer programming language.', '1987', './xbase'),
	('392', 'Systems', 'WPlus', 'WPlus is a systems programming language that supports high-level programming and low-level programming.', '2016', './wplus'),
	('393', 'Systems', 'WebAssembly', '"WebAssembly (often abbreviated wasm) is a binary instruction format for a stack-based virtual machine. It''s intended as a portable target for the compilation of high-level languages like C, C++, and Rust, enabling deployment on web for client and server applications."', '2015', './webassembly'),
	('394', 'Object-oriented', 'Wendy', 'Wendy is an object-oriented programming language.', '2000', './wendy'),
	('395', 'Object-oriented', 'Winterp', 'Winterp is an object-oriented scripting language with a focus on AI application development.', '1988', './winterp'),
	('396', 'Object-oriented', 'Wizard', 'Wizard is an object-oriented programming language.', '2005', './wizard'),
	('397', 'Object-oriented', 'Wolf', 'Wolf is an object-oriented programming language that supports both static and dynamic typing.', '2008', './wolf'),
	('398', 'Object-oriented', 'Word', '''Word'' is an object-oriented programming language.', '1998', './word'),
	('399', 'Object-oriented', 'Wren', '"Wren is a small, fast, class-based concurrent scripting language. Think Smalltalk in a Lua-sized package with a dash of Erlang and wrapped up in a familiar, modern syntax."', '2013', './wren'),
	('400', 'Scripting', 'X', '''X'' is a scripting language.', '2017', './x'),
	('404', 'Object-oriented', 'XOTcl', 'XOTcl (Extended Object Tcl) is an object-oriented scripting language based on Tcl. It was designed as a value added replacement for OTcl.', '1999', './xotcl'),
	('403', 'Object-oriented', 'XBL', '"XBL is an XML-based markup language used to declare the behavior and look of ''XUL-widgets'', a set of user interface elements."', '1998', './xbl'),
	('405', 'Systems', 'XObject', 'XObject is a systems-oriented programming language.', '2008', './xobject'),
	('406', 'Query', 'XPath', '"XPath (XML Path Language) is a query language for selecting nodes from an XML document. In addition, XPath may be used to compute values (e.g., strings, numbers, or Boolean values) from the content of an XML document."', '1999', './xpath'),
	('410', 'Object-oriented', 'Xcode', 'Xcode is an integrated development environment (IDE) for macOS that contains a suite of software development tools developed by Apple.', '2003', './xcode'),
	('411', 'Natural', 'Xiang Chinese', '"Xiang Chinese, also known as Hunanese, is a group of linguistic varieties spoken in Hunan province, China."', '1000', './xiang_chinese'),
	('412', 'Object-oriented', 'XmlAttribute', 'XmlAttribute is a class in .NET framework that represents an attribute in an XML document.', '2012', './xmlattribute'),
	('413', 'Object-oriented', 'Xojo', '"Xojo is an object-oriented programming language for building applications on several platforms including Windows, macOS, Linux and more."', '1997', './xojo'),
	('414', 'Object-oriented', 'Xtend', '"Xtend is an open-source, statically-typed, object-oriented programming language for the Java Virtual Machine (JVM) originally developed by Eclipse."', '2011', './xtend'),
	('415', 'Object-oriented', 'Y', '''Y'' is an object-oriented language developed as a research project.', '2002', './y'),
	('416', 'Object-oriented', 'YAP', 'Yet Another Prolog (YAP) is a high-performance Prolog compiler developed in Portugal.', '2006', './yap'),
	('417', 'Systems', 'YARV', 'Yet Another Ruby VM (YARV) is a bytecode interpreter that was developed for the Ruby programming language.', '2000', './yarv'),
	('418', 'Esoteric', 'YROF', '"YROF is an esoteric programming language, a variant of Rongorongo. Rongorongo is a glyphic script. The basis of YROF is to construct characters using code."', '2007', './yrof'),
	('419', 'Systems', 'YaBasic', '"YaBasic, or Yet Another Basic, is a free and open-source BASIC interpreter for UNIX platforms."', '1992', './yabasic'),
	('420', 'Markup', 'Yaml', '"Yaml, or YAML Ain''t Markup Language, is a human-readable data serialization language."', '2001', './yaml'),
	('421', 'Object-oriented', 'Yasmo', 'Yasmo is a general-purpose object-oriented programming language.', '2016', './yasmo'),
	('422', 'Systems', 'Yoda', 'Yoda is a scripting language designed for process automation on Windows systems.', '1985', './yoda'),
	('423', 'Object-oriented', 'Yorick', '"Yorick is an interpreted programming language designed for numerics, graph plotting, and steering large scientific simulation codes."', '1996', './yorick'),
	('424', 'Object-oriented', 'Ysh', 'Ysh is an object-oriented shell based on Scheme syntax.', '1995', './ysh'),
	('425', 'Object-oriented', 'Yuche', 'Yuche is an object-oriented programming language which was developed in 1991.', '1991', './yuche'),
	('426', 'Natural', 'Cantonese', '"Yue Chinese, also known as Cantonese, is a language of the Chinese language family, spoken in Southern China and Hong Kong."', '100', './cantonese'),
	('428', 'Specification', 'Z notation', 'The Z notation is a formal specification language used for describing and modeling computing systems.', '1974', './z_notation'),
	('429', 'Parallel', 'ZPL', 'ZPL is a parallel programming language that was developed at the University of Washington to craft a simple and efficient parallel computing platform.', '2001', './zpl'),
	('430', 'Object-oriented', 'ZScript', 'ZScript is the scripting language used in the game engine for the video game Doom.', '1998', './zscript'),
	('431', 'Systems', 'ZTerm', 'ZTerm is a terminal emulation program for the Macintosh and was used for connecting to bulletin board systems.', '1981', './zterm'),
	('432', 'Object-oriented', 'Zend', 'Zend is a strongly typed high-performance scripting language used for Web development.', '2019', './zend'),
	('435', 'Object-oriented', 'Znd', 'Znd is an object-oriented programming language that was developed in 2018.', '2018', './znd'),
	('436', 'Object-oriented', 'Zograf', 'Zograf is an object-oriented programming language that was created in 2017.', '2017', './zograf'),
	('437', 'Natural', 'Zulu', 'Zulu is a Bantu language originated from Nguni tribes and spoken in South Africa. Its development can be traced back to the 17th century.', '1600', './zulu'),
	('427', 'Object-oriented', 'Z', '"Z is a statically typed, strongly encapsulated, object-oriented programming language."', '2005', './z'),
	('439', 'Object-oriented', 'Zephyr', 'Zéphyr is an object-oriented programming language that was created in 1971.', '1971', './zephyr'),
	('438', 'Object-oriented', 'Zz', 'Zz is an object-oriented programming language that was developed in 2017.', '2017', './zz'),
	('440', 'Procedural', 'dBase', 'dBase is one of the first widely used database management systems (DBMS) for microcomputers.', '1981', './dbase'),
	('1', 'Array', 'A+', '"Developed at Morgan Stanley in the late 1980s, A+ is a derivative of the APL programming languages, with additional enhancements and extensions."', '1990', './a+'),
	('3', 'Functional Compiler', 'A-0', '"A-0, developed by Grace Murray Hopper, uses arithmetic, links pre-compiled subroutines into memory to run a program, making it the first compiler ever."', '1951', './a-0'),
	('20', 'Constraint logic', 'Alma-0', '"Alma-0 is a declarative programming language which combines constraint programming, logical programming and concurrent programming."', '1996', './alma-0'),
	('28', 'Low-level', 'Assembly', '"Assembly language is a low-level programming language for a computer, or other programmable device, in which there is a very strong correspondence between the language and the architecture''s machine code instructions."', '1949', './assembly'),
	('43', 'Object-oriented', 'Bistro', 'Bistro is a variant of the Smalltalk programming language that is oriented towards component-based programming.', '2006', './bistro'),
	('48', 'Object-oriented', 'BlueJ', '"BlueJ is an integrated development environment (IDE) for the Java programming language, developed mainly for educational purposes."', '1999', './bluej'),
	('443', 'Systems', 'C', '"General-purpose, imperative computer programming language, supporting structured programming, lexical variable scope and recursion, while a static type system prevents many unintended operations"', '1972', './c'),
	('444', 'Object-oriented', 'C++', '"Compiled, general-purpose programming language. It is free-form and supports object-oriented, imperative and generic programming"', '1980', './c++'),
	('61', 'Object-oriented', 'Charm', 'Charm is an object-oriented programming language that combines the best features of all the members of the Lisp family of languages.', '1989', './charm'),
	('81', 'Object-relational', 'Delphi', '"Delphi is a high-level, compiled, strongly typed language used to generate platform-specific native code."', '1995', './delphi'),
	('291', 'Object-oriented', 'Duce', 'Duce is an object-oriented language that was launched in 2004.', '2004', './duce'),
	('232', 'Object-oriented', 'Java', '"Java is a high-level, general-purpose programming language that is designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere."', '1995', './java'),
	('253', 'Object-oriented', 'MUMPS', '"MUMPS (Massachusetts General Hospital Utility Multi-Programming System), is a general-purpose programming language that provides ACID (Atomic, Consistent, Isolated, and Durable) transaction processing."', '1966', './mumps'),
	('260', 'Natural', 'Min Nan Chinese', '"Min Nan Chinese, also known as Southern Min, is a group of Chinese varieties spoken in the southern part of Fujian Province in Southeastern China and neighboring areas."', '200', './min_nan_chinese'),
	('284', 'Object-oriented', 'Paia', '"Established in 2005, Paia is an object-oriented programming language."', '2005', './paia'),
	('293', 'Natural', 'Polish', '"Polish is a West Slavic language spoken primarily by the people in Poland, dating back to 900."', '900', './polish'),
	('301', 'Object-oriented', 'PureScript', '"PureScript is a small, strongly-typed programming language that compiles to efficient and readable JavaScript, established in 2011."', '2011', './purescript'),
	('334', 'Typesetting', 'TeX', '"TeX is a typesetting system that is widely used in academia, especially in mathematics, computer science, economics, engineering, physics, statistics, and quantitative psychology."', '1978', './tex'),
	('351', 'Typesetting', 'Troff', 'Troff is a document processing system developed by AT&T for the Unix operating system.', '197', './troff'),
	('352', 'Natural', 'Tunisian Arabic', '"Tunisian Derja is fundamentally Arabic but has a distinctive vocabulary, grammar and pronunciation. It is a branch of Derja."', '700', './tunisian_arabic'),
	('358', 'Natural', 'Ukrainian', '"Ukrainian is an East Slavic language. It is the official state language of Ukraine and one of the three official languages in the unrecognized state of Transnistria, the other two being Romanian and Russian."', '1200', './ukrainian'),
	('401', 'Concurrent', 'X10', '"X10 is a programming language being developed by IBM at the Thomas J. Watson Research Center as part of the Productive, Easy-to-use, Reliable Computing System (PERCS) project funded by DARPA''s High Productivity Computing Systems ( program."', '2005', './x10'),
	('441', 'Software tools', 'ocamllex', 'ocamllex is a lexical analyzer generator for the OCaml programming language.', '1996', '/ocamllex');
